services:
  grafana:
    extends:
      file: .config/docker-compose-base.yaml
      service: grafana
    container_name: 'harv-logs'
    volumes:
      - ./dist:/var/lib/grafana/plugins/harv-logs
      - ./rules/rca-rules.yaml:/var/lib/grafana/plugins/harv-logs/rules/rca-rules.yaml:ro
      - ./provisioning:/etc/grafana/provisioning
      - .:/root/harv-logs
    environment:
      RCA_RULES_PATH: /var/lib/grafana/plugins/harv-logs/rules/rca-rules.yaml
